# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

jobs:
  build:
    docker:
      - image: cimg/php:8.1.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: mkdir build

      - run: phpdbg ./vendor/bin/phpunit --coverage-clover build/coverage.xml --coverage-html build/coverage --log-junit build/junit.xml

      - run: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: build

      - store_artifacts:
          path: build/coverage-report
