<?php

declare(strict_types=1);

namespace Smpl\Inspector\Types;

use Smpl\Inspector\Contracts\Type;
use Smpl\Inspector\Factories\TypeFactory;

class BoolType extends BaseType
{
    public function getName(): string
    {
        return 'bool';
    }

    public function matches(mixed $value): bool
    {
        return is_bool($value);
    }

    public function accepts(Type|string $type): bool
    {
        if (! ($type instanceof Type)) {
            $type = TypeFactory::getInstance()->make($type);
        }

        if ($type instanceof FalseType) {
            return true;
        }

        return parent::accepts($type); // TODO: Change the autogenerated stub
    }
}